#cg-deploy-prometheus-staging-git-branch: test-deploy-jammy
cg-deploy-prometheus-staging-git-branch: main
cg-deploy-prometheus-staging-git-url: https://github.com/cloud-gov/cg-deploy-prometheus.git
# cg-deploy-prometheus-git-branch: test-deploy-jammy
cg-deploy-prometheus-git-branch: main
cg-deploy-prometheus-git-url: https://github.com/cloud-gov/cg-deploy-prometheus.git

prometheus-release-git-branch: master
prometheus-release-version-filter: v27.*
prometheus-release-git-url: https://github.com/bosh-prometheus/prometheus-boshrelease

pipeline-tasks-git-branch: master
pipeline-tasks-git-url: https://github.com/cloud-gov/cg-pipeline-tasks.git

slack-icon-url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=40
