- type: remove
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=elasticsearch_exporter
- type: remove
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=firehose
- type: remove
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=cf
- type: remove
  path: /instance_groups/name=prometheus/jobs/name=cf_exporter
- type: remove
  path: /instance_groups/name=prometheus/jobs/name=firehose_exporter