azs: [z1]
environment: production
domain: fr.cloud.gov
logsearch_file_size_threshold: 3000000
logsearch_log_count_threshold: 30000
logsearch_ratio_threshold: 50
blackbox-targets:
- https://login.fr.cloud.gov
- https://api.fr.cloud.gov
- https://test-java.app.cloud.gov
- https://test-nodejs.app.cloud.gov
- https://test-dotnet-core.app.cloud.gov
- https://test-python-flask.app.cloud.gov
- https://test-php.app.cloud.gov
- https://test-ruby-padrino.app.cloud.gov
- https://test-ruby-sinatra.app.cloud.gov
- https://www.fdic.gov
- https://www.fec.gov
