azs: [z1]
environment: production # this is just for deployment name and bosh resource types, so we want prod
domain: fr.wb.cloud.gov #focus on 1 cf ATM
logsearch_file_size_threshold: 3000000
logsearch_log_count_threshold: 30000
logsearch_ratio_threshold: 50
blackbox-targets:
- https://api.fr.wb.cloud.gov